include:
  - project: adarlan/gitlab-pipeline-template-for-terraform-module
    ref: main
    file: template.gitlab-ci.yml

variables:
  ALLOW_CHECK_FORMAT_FAILURE: 'false'
  MANUALLY_CREATE: 'true'
  AUTO_CREATE: 'true'
  MANUALLY_DESTROY: 'true'
  AUTO_DESTROY_ON_FAILURE: 'true'
  AUTO_DESTROY_AFTER_CREATE: 'false'
